title: Khan Academy
#logo
description: This is a very educational site for helping on 7th Grade Khan Academy Work. Helpful to kids with courses full of teaching on basic units like proportional relationships, rates, percentages, integers, rational numbers, expressions, equations, geometry, and statistics, probability and more. This is here to test skills and help 7th graders with math skills to improve real-world problem solving.
#show_downloads: true
theme: jekyll-theme-midnight
